trigger:
- main

pool: Default

stages:
- stage: 
  displayName: Prebuild stage
  jobs:
  - job: Sbt_clean
    displayName: 'Clean sbt'
    steps:
    - bash: sbt clean
  - job: Sbt_update
    displayName: 'Update sbt'
    steps:
    - bash: sbt update

# - stage: 
#   displayName: Test stage
#   jobs:
#   - job: Sbt_test
#     displayName: 'Test'
#     steps:
#     - bash: sbt test
#       displayName: 'Test'

- stage: 
  displayName: Build stage
  jobs:
  - job: Sbt_Build
    displayName: 'Build'
    steps:
    - script: sbt executable
      displayName: 'Build'
  - job: Deploy 
    displayName: 'Deploy'
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure for Students(3e3acbb9-1a34-409b-868f-db65dbca2e5b)'
        appType: 'webAppLinux'
        WebAppName: 'gitbucket2'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/target/executable/gitbucket.war'
        RuntimeStack: 'TOMCAT|9.0-java11'

# - stage: 
#   displayName: Deploy stage
#   jobs:
