trigger:
- main

pool: Default

stages:
- stage: 
  displayName: Prebuild stage
  jobs:
  - job: Sbt_clean
    displayName: 'Clean sbt'
    steps:
    - script: sbt clean
  - job: Sbt_update
    displayName: 'Update sbt'
    steps:
    - script: sbt update

- stage: Test
  displayName: Test stage
  jobs:
  - job: Sbt_test
    displayName: 'Test'
    steps:
    - script: sbt test

- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    steps:
    - script: sbt executable
      displayName: 'Build'
    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/executable/gitbucket.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

- stage: deploy
  dependsOn: build
  displayName: Deploy stage
  jobs:
  - job: Deploy 
    steps:
    - download: current
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure for Students(3e3acbb9-1a34-409b-868f-db65dbca2e5b)'
        appType: 'webAppLinux'
        WebAppName: 'gitbucket2'
        packageForLinux: '$(Pipeline.Workspace)/drop/target/executable/gitbucket.war'
        RuntimeStack: 'TOMCAT|9.0-java11'