trigger:
- master
pool: Default
steps:
- script: sbt clean
  displayName: 'Running $ sbt clean'
- script: sbt update
  displayName: 'Running $ sbt update'
#- script: sbt test
#  displayName: 'Running $ sbt test'
- script: sbt executable
  displayName: 'Running $ sbt executable'
- script: pwd
  displayName: 'Running $ pwd'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(3e3acbb9-1a34-409b-868f-db65dbca2e5b)'
    appType: 'webAppLinux'
    appName: 'gitbucket2'
    deployToSlotOrASE: true
    resourceGroupName: 'gitbucket2'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/target/executable/gitbucket.war'
    runtimeStack: 'TOMCAT|8.5-jre8'