trigger:
- master
pool: Default
steps:
- script: sbt clean
  displayName: 'Running $ sbt clean'
- script: sbt update
  displayName: 'Running $ sbt update'
#- script: sbt test
#  displayName: 'Running $ sbt test'
- script: sbt executable
  displayName: 'Running $ sbt executable'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(3e3acbb9-1a34-409b-868f-db65dbca2e5b)'
    appType: 'webAppLinux'
    WebAppName: 'gitbucket2'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/target/executable/gitbucket.war'
    RuntimeStack: 'TOMCAT|9.0-java11'